### ISSUE TITLE
How to use Hydra without define keymap in `head`

### ISSUE THREAD

**Issue by bangedorrunt** [anuvyklack/hydra.nvim#43]
I'm migrating to hydra from which-key. With the later, I just need define key name and description inside which-key module without having to defining keybinding inside. Is it possible with `hydra`. Put `nil` in head's rhs doesn't work because keymap is not activated :(

**Comment by haolian9** [comment]
seems you just need to bind a no-op to the body. this config might help
```
      invoke_on_body = true,
      on_enter = function() end,
```

**Comment by anuvyklack** [comment]
You can consider hydra is a one big keybinding, that's bind to `<Leader>f`.  You also have another `<Leader>ff` keymap that do invoke Telescope file-finder.  So when you press `<Leader>f` Vim will wait `timeoutlen` (see `:help timeoutlen`) seconds for continuation (since you have another longer keymap with the same prefix) and activate hydra.  The hydra binds its heads something like (for `f` head): `<Plug>(Hydra2)f` and it has nothing in common with `<Leader>ff>`. The `<Leader>f` keymap is another keymap, that only activates the hydra. But you can bind one keymap to another using `remap` keymap option:

```lua
Hydra({
   ...
   mode = 'n',
   body = '<Leader>f',
   heads = {
      { 'f', '<Leader>ff', { remap = true } },
      ...
   }
})

-- In `telescope.lua` module

-- No need for `noremap = true` here, since it is the default.
vim.keymap.set({"n"}, "<Leader>ff", "<Cmd>Telescope find_files<CR>")
```
