### ISSUE TITLE
Simple Hydra to Move to / Rezize windows

### ISSUE THREAD

**Issue by ziontee113** [anuvyklack/hydra.nvim#9]
First of all, thank you so much for this stellar plugin. This plugin means so much to me. Thank you again for making this :100: 
When I try it out, then I think to myself "Is it possible for a Hydra to activate another Hydra". And it's there! `Hydra:activate()`

Here I have my simple Hydra to move / resize windows, without interfering with `<C-w>s` & `<C-w>v`.
I want to make a quick video about this. Do you have any suggestions what should I include / emphasize for the viewers? Thank you :)

```lua
local Hydra = require("hydra")

Hydra({
	name = "Change / Resize Window",
	mode = { "n" },
	body = "<C-w>",
	config = {
		color = "pink",
	},
	heads = {
		-- move between windows
		{ "<C-h>", "<C-w>h" },
		{ "<C-j>", "<C-w>j" },
		{ "<C-k>", "<C-w>k" },
		{ "<C-l>", "<C-w>l" },

		-- resizing window
		{ "H", "<C-w>3<" },
		{ "L", "<C-w>3>" },
		{ "K", "<C-w>2+" },
		{ "J", "<C-w>2-" },

		-- equalize window sizes
		{ "e", "<C-w>=" },

		-- close active window
		{ "Q", ":q<cr>" },
		{ "<C-q>", ":q<cr>" },

		-- exit this Hydra
		{ "q", nil, { exit = true, nowait = true } },
		{ ";", nil, { exit = true, nowait = true } },
		{ "<Esc>", nil, { exit = true, nowait = true } },
	},
})
```

**Comment by anuvyklack** [comment]
Thank you for kind words:)

Better use this, because it can't close last window
```lua
{ 'Q', '<Cmd>try | close | catch | endtry<CR>' },
```
then this, which can quit Vim accidentally:
```lua
{ "Q", ":q<cr>" },
```

**Comment by ziontee113** [comment]
Thanks man! I didn't know `try | close | catch` exists.

**Comment by ziontee113** [comment]
I did a little video for this example: https://youtu.be/KSBzeCGnqYM
Is there any Hydra features that I should cover in the future videos? I'd love your input on this.

**Comment by Frederick888** [comment]
Just want to chime in that I found Hydra works super well with https://github.com/mrjones2014/smart-splits.nvim

```lua
local Hydra = require('hydra')
local splits = require('smart-splits')
Hydra({
  name = "Split movements and resizing",
  mode = 'n',
  body = '<C-w>',
  config = {
    timeout = 250,
  },
  heads = {
    { 'h', splits.move_cursor_left },
    { 'j', splits.move_cursor_down },
    { 'k', splits.move_cursor_up },
    { 'l', splits.move_cursor_right },
    { 'H', splits.resize_left },
    { 'J', splits.resize_down },
    { 'K', splits.resize_up },
    { 'L', splits.resize_right },
  },
})
```

Finally it can work exactly the same as how tmux works 🎉

**Comment by Frederick888** [comment]
I actually have a question, which is probably more about Neovim Lua rather than Hydra specifically: How do you recover from an error and prevent Hydra hint from being stuck?

I sometimes muscle-memories Ctrl-W h/j/k/l in history windows, e.g. `q:`, `q/`, and usually without Hydra it just prints out an error message `E11: Invalid in command-line window; <CR> executes, CTRL-C quits`.

Using Hydra however, this prints out a long stack trace and Hydra is stuck on screen afterwards:

```lua
local Hydra = require('hydra')

local function wincmd_func(cmd)
  return function()
    vim.fn.execute('wincmd ' .. cmd)
  end
end

Hydra({
  name = "Split movements and resizing",
  mode = 'n',
  body = '<C-w>',
  config = {
    timeout = 250,
  },
  heads = {
    { 'h', wincmd_func('h') },
    { 'j', wincmd_func('j') },
    { 'k', wincmd_func('k') },
    { 'l', wincmd_func('l') },
  },
})
```

![image](https://user-images.githubusercontent.com/4507647/175967346-beb33907-d378-47e4-9ecc-4819a556e081.png)
![image](https://user-images.githubusercontent.com/4507647/175967407-31a9f799-e987-4ce8-9a53-f533e0e0a315.png)

I tried things like `vim.fn.execute('wincmd ' .. cmd, 'silent!')` `pcall(vim.api.nvim_command, string.format('call execute("wincmd %s", "silent!")', cmd))` but none of them worked. Any suggestions?

**Comment by anuvyklack** [comment]
Try this:
```lua
      { 'k', [[<cmd>try | wincmd k | catch /^Vim\%((\a\+)\)\=:E11:/ | close | endtry<CR>]] },
```

**Comment by Frederick888** [comment]
> Try this:
> 
> ```lua
> { 'k', [[<cmd>try | wincmd k | catch /^Vim\%((\a\+)\)\=:E11:/ | close | endtry<CR>]] },
> ```
> 
> Check wiki for my variant of such hydra.

That worked perfectly! Thank you!
